[package]
name = "av"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
authors = ["Redstone <redstone@fds.moe>"] 
description = "A Rust procedural macro for tracking API version history and deprecation warnings. " 
license = "MIT" 
repository = "https://github.com/Field-of-Dream-Studio/api_version" 
categories = ["development-tools", "rust-patterns"]
keywords = ["api", "versioning", "deprecation", "documentation", "macro"] 
homepage = "https://fds.rs/" 

[lib]
proc-macro = true

[features]
deprecated_for_unstable = []

[dependencies]
