[package]
name = "av"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
deprecated_for_unstable = []

[dependencies]

[[example]]
name = "example1_minimal"
path = "examples/example1_minimal.rs"

[[example]]
name = "example2_full"
path = "examples/example2_full.rs"

[[example]]
name = "example3_history"
path = "examples/example3_history.rs"

[[example]]
name = "example4_warning_unstable"
path = "examples/example4_warning_unstable.rs"

[[example]]
name = "example5_warning_deprecated"
path = "examples/example5_warning_deprecated.rs"
